export enum BoroughCode {
  AC = 'AC',
  ANJ = 'ANJ',
  CDNNDG = 'CDNNDG',
  IBZSGV = 'IBZSGV',
  LCH = 'LCH',
  LSL = 'LSL',
  MTL = 'MTL',
  MHM = 'MHM',
  MTN = 'MTN',
  OUT = 'OUT',
  PMR = 'PMR',
  PFDROX = 'PFDROX',
  RDPPAT = 'RDPPAT',
  RPP = 'RPP',
  SLN = 'SLN',
  SLR = 'SLR',
  SO = 'SO',
  VM = 'VM',
  VRD = 'VRD',
  VSMPE = 'VSMPE'
}
